spring.application.name=AI Resume Analyzer

server.port=8080

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

gemini.api.key=AQ.Ab8RN6JUSreZ_u3q4s3LW3hABgZpUXeDrwpp64iuw4Jzlih_aw